language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t sdontireddy/docker-react -f Dockerfile.Dev .

script:
  - docker run -e CI=true sdontireddy/docker-react npm run test
